### ISSUE TITLE
Gradle not found

### ISSUE THREAD

**Issue by gruessung** [iammert/FastGCM#11]
I already get

Error:Failed to find: com.github.iammert:FastGCM:1.1
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>

Edit:
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not resolve com.github.iammert:FastGCM:1.1.
     Required by:
         ParkeninErfurt:app:unspecified
      > Could not GET 'https://jitpack.io/com/github/iammert/FastGCM/1.1/FastGCM-1.1.pom'.
         > peer not authenticated

**Comment by iammert** [comment]
I updated it. Can you check new version.
`compile 'com.github.iammert:FastGCM:1.2'`
