### ISSUE TITLE
How to get deviceId from service

### ISSUE THREAD

**Issue by sagits** [iammert/FastGCM#8]
Hi, i'm a little confused, if i just start the service it will automatically register on gcm? How can i get the deviceId from service or from activity when using a service? Thanks in advance.

**Comment by iammert** [comment]
onDeviceRegistered(String token) interface method will provide you a token to send push notification.

**Comment by sagits** [comment]
Thanks, but this method is not present on the service interface, is it?

**Comment by iammert** [comment]
it is not on service. Actually I think readme is so clean about implementing service and get token.

**Comment by iammert** [comment]
//call this onCreate()
GCMManager.getInstance(this).registerListener(this);

public class MainActivity extends Activity implements GCMListener{

  @Override
  public void onDeviceRegisted(String token) {}

  @Override
  public void onMessage(String from, Bundle bundle) {}

  @Override
  public void onPlayServiceError() {}
}

**Comment by davkap92** [comment]
Hi thanks for making this but I must agree its a bit unclear
Are you saying it must be a service or thats an option?
And we don't implement in MainActivity if we use CustomGCMService?
Thanks
